import fs from 'node:fs';
import path from 'node:path';
import type { AirlineSuggestion } from '@trek/shared';

/**
 * Carrier designator lookups for the flight tracker.
 *
 * Turns what a booking actually contains — an airline NAME ("Austrian
 * Airlines") plus a bare flight number ("254") — into the identifiers the two
 * upstream APIs need: the IATA flight number (OS254) for AeroDataBox and the
 * ICAO ATC call sign (AUA254) for adsb.fi.
 *
 * Backed by `assets/airlines.json`, generated by `scripts/build-airlines.mjs`
 * from Wikidata + OpenFlights. Loaded lazily and cached for the process
 * lifetime, mirroring `airportService`.
 */

interface AirlineData {
  /** normalised name/alias -> IATA */
  nameToIata: Record<string, string>;
  /** normalised name/alias -> ICAO (covers carriers with no IATA code) */
  nameToIcao: Record<string, string>;
  iataToIcao: Record<string, string>;
  icaoToIata: Record<string, string>;
  /** IATA -> display name */
  names: Record<string, string>;
  /** ICAO -> ATC call sign */
  callsigns: Record<string, string>;
}

export interface ResolvedAirline {
  iata: string;
  icao: string;
  name: string | null;
  callsign: string | null;
}

const EMPTY: AirlineData = {
  nameToIata: {}, nameToIcao: {}, iataToIcao: {}, icaoToIata: {}, names: {}, callsigns: {},
};

let cache: AirlineData | null = null;
/** IATA -> suggestion row; the searchable carrier list (one row per carrier). */
let carriers: Map<string, AirlineSuggestion> | null = null;
/** normalised alias -> IATA, for name searches that are not the display name. */
let aliasToIata: Map<string, string> | null = null;

const IATA_RE = /^[A-Z0-9]{2}$/;
const ICAO_RE = /^[A-Z]{3}$/;

/**
 * Match however a booking spells the airline: case-, diacritic- and
 * punctuation-insensitive. MUST stay identical to `normName` in
 * scripts/build-airlines.mjs — the asset's keys are normalised with it, so any
 * divergence makes every name lookup silently miss.
 */
export function normaliseAirlineName(s: string | null | undefined): string {
  return String(s || '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function load(): AirlineData {
  if (cache) return cache;
  const file = path.join(__dirname, '..', '..', 'assets', 'airlines.json');
  if (!fs.existsSync(file)) {
    console.warn('[airlines] airlines.json missing — run `node scripts/build-airlines.mjs`');
    cache = EMPTY;
  } else {
    try {
      cache = { ...EMPTY, ...(JSON.parse(fs.readFileSync(file, 'utf8')) as Partial<AirlineData>) };
    } catch (err) {
      console.warn('[airlines] airlines.json unreadable — falling back to no dataset', err);
      cache = EMPTY;
    }
  }

  // One searchable row per IATA carrier. `names` is keyed by IATA, so the map is
  // inherently duplicate-free; every alias resolves back into the same row.
  carriers = new Map();
  for (const [iata, name] of Object.entries(cache.names)) {
    const icao = cache.iataToIcao[iata] || null;
    carriers.set(iata, { iata, icao, name, callsign: (icao && cache.callsigns[icao]) || null });
  }
  aliasToIata = new Map(Object.entries(cache.nameToIata));
  return cache;
}

/**
 * Resolve a booking's airline field (a free-text name, an explicit code, or
 * both) to its designators. An explicit code wins over the name — the traveller
 * typed it, and shared/recycled names are the ambiguous part.
 */
export function resolveAirline(
  name?: string | null,
  code?: string | null,
): ResolvedAirline | null {
  const data = load();
  let iata = '';
  let icao = '';

  if (code) {
    const c = String(code).toUpperCase().replace(/[^A-Z0-9]/g, '');
    if (IATA_RE.test(c)) iata = c;
    else if (ICAO_RE.test(c)) { icao = c; iata = data.icaoToIata[c] || ''; }
  }
  // No usable code — fall back to the name, normalised the same way the
  // generator normalised the asset's keys.
  if (!iata && !icao && name) {
    const key = normaliseAirlineName(name);
    if (key) {
      iata = data.nameToIata[key] || '';
      if (!iata) icao = data.nameToIcao[key] || '';
    }
  }
  if (!iata && !icao) return null;

  if (!icao) icao = data.iataToIcao[iata] || '';
  if (!iata && icao) iata = data.icaoToIata[icao] || '';
  return {
    iata,
    icao,
    name: (iata && data.names[iata]) || null,
    callsign: (icao && data.callsigns[icao]) || null,
  };
}

/**
 * ICAO designator for a flight number prefix. An explicit 3-letter code wins;
 * otherwise the IATA prefix is mapped through the dataset. Returns '' when
 * unknown, so callers can simply skip the call-sign lookup.
 */
export function iataToIcao(iata?: string | null, code?: string | null): string {
  const data = load();
  if (code) {
    const c = String(code).toUpperCase().replace(/[^A-Z]/g, '');
    if (ICAO_RE.test(c)) return c;
  }
  if (iata) return data.iataToIcao[String(iata).toUpperCase()] || '';
  return '';
}

/**
 * Autocomplete for the airline field. Ranked exact code > exact name >
 * prefix > substring, and deduplicated by carrier: "Lufthansa Cargo" and
 * "Deutsche Lufthansa" both hit the single LH row rather than filling the
 * dropdown with the same airline three times.
 */
export function searchAirlines(query: string, limit = 12): AirlineSuggestion[] {
  load();
  const raw = String(query || '').trim();
  if (!raw) return [];
  const q = raw.toLowerCase();
  const upper = raw.toUpperCase().replace(/[^A-Z0-9]/g, '');
  const normQ = normaliseAirlineName(raw);

  const scores = new Map<string, number>();
  const bump = (iata: string | undefined, score: number) => {
    if (!iata || !carriers!.has(iata)) return;
    if ((scores.get(iata) ?? 0) < score) scores.set(iata, score);
  };

  // Exact designator: the user typed a code, so nothing else can rank higher.
  if (IATA_RE.test(upper)) bump(upper, 100);
  if (ICAO_RE.test(upper)) bump(cache!.icaoToIata[upper], 100);
  // Exact name (any spelling the dataset knows).
  if (normQ) bump(aliasToIata!.get(normQ), 90);

  for (const [iata, c] of carriers!) {
    const name = c.name.toLowerCase();
    if (name.startsWith(q)) bump(iata, 70);
    else if (upper && iata.startsWith(upper)) bump(iata, 65);
    else if (name.includes(q)) bump(iata, 40);
  }
  // Alias prefix/substring matches, so trade names the display name omits still
  // find their carrier — but ranked below a real display-name match.
  if (normQ) {
    for (const [alias, iata] of aliasToIata!) {
      if ((scores.get(iata) ?? 0) >= 50) continue;
      if (alias.startsWith(normQ)) bump(iata, 50);
      else if (alias.includes(normQ)) bump(iata, 30);
    }
  }

  return [...scores.entries()]
    .sort((a, b) => b[1] - a[1] || carriers!.get(a[0])!.name.localeCompare(carriers!.get(b[0])!.name))
    .slice(0, Math.max(0, limit))
    .map(([iata]) => carriers!.get(iata)!);
}

/** Test seam — drops the memoised dataset so a fixture can be re-read. */
export function __resetAirlineCache(): void {
  cache = null;
  carriers = null;
  aliasToIata = null;
}
